import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { WebView } from "react-native-webview";

import { ScreenContainer } from "@/components/screen-container";
import { COLORS, IconCircle, Tag } from "@/components/lms-ui";
import { isAllowedOfficialPortalUrl, OFFICIAL_LAND_PORTALS } from "@/lib/amin-toolkit";

export default function LandRecordsScreen() {
  const router = useRouter();
  const { portal } = useLocalSearchParams<{ portal?: string }>();
  const selected = OFFICIAL_LAND_PORTALS.find((item) => item.id === portal);
  const [blockedMessage, setBlockedMessage] = useState<string | null>(null);
  if (selected && Platform.OS !== "web") return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.viewerHeader}><Pressable accessibilityRole="button" accessibilityLabel="Return to official portal directory" onPress={() => router.replace("/toolkit/land-records")} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={COLORS.indigo} /></Pressable><View style={{ flex: 1 }}><Text style={styles.viewerTitle}>{selected.title}</Text><Text style={styles.viewerSub}>Official portal · in-app only</Text></View><Tag label="OFFICIAL" tone="green" /></View>{blockedMessage ? <View style={styles.blocked}><MaterialIcons name="shield" size={22} color={COLORS.saffron} /><Text style={styles.blockedText}>{blockedMessage}</Text><Pressable onPress={() => setBlockedMessage(null)} style={styles.reload}><Text style={styles.reloadText}>Return to official portal</Text></Pressable></View> : <WebView source={{ uri: selected.url }} originWhitelist={["https://*"]} style={styles.viewer} javaScriptEnabled domStorageEnabled setSupportMultipleWindows={false} onShouldStartLoadWithRequest={(request) => { const allowed = isAllowedOfficialPortalUrl(request.url); if (!allowed) setBlockedMessage("This link is outside the reviewed official portal directory, so it was blocked to keep browsing safely inside Amin Ka Master."); return allowed; }} />}</ScreenContainer>;
  return <ScreenContainer className="px-5" edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Return to Amin Toolkit" onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={COLORS.indigo} /></Pressable><View><Text style={styles.eyebrow}>REVIEWED DIRECTORY</Text><Text style={styles.title}>State Land Records</Text></View></View><View style={styles.notice}><Tag label="OFFICIAL HOSTS ONLY" tone="green" /><Text style={styles.noticeText}>Open a reviewed government portal inside the app. Links outside the official directory are blocked instead of handing off to a browser.</Text></View>{Platform.OS === "web" ? <View style={styles.webNotice}><MaterialIcons name="phone-android" size={24} color={COLORS.indigo} /><Text style={styles.webNoticeTitle}>Open this directory in the mobile app</Text><Text style={styles.webNoticeText}>Official portal browsing is intentionally limited to the native in-app WebView, where external navigation can be blocked.</Text></View> : null}{OFFICIAL_LAND_PORTALS.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Open ${item.title}`} onPress={() => router.push({ pathname: "/toolkit/land-records", params: { portal: item.id } } as never)} style={({ pressed }) => [styles.portal, pressed && styles.pressed]}><IconCircle icon="account-balance" size={44} color={COLORS.indigo} background={COLORS.indigoSoft} /><View style={{ flex: 1 }}><Text style={styles.portalState}>{item.state.toUpperCase()}</Text><Text style={styles.portalTitle}>{item.title}</Text><Text style={styles.portalBody}>{item.note}</Text></View><MaterialIcons name="chevron-right" size={25} color={COLORS.muted} /></Pressable>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 28, gap: 13 }, header: { flexDirection: "row", alignItems: "center", gap: 10 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: COLORS.indigoSoft, justifyContent: "center", alignItems: "center" }, eyebrow: { color: COLORS.earth, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: COLORS.ink, fontSize: 22, fontWeight: "900", marginTop: 2 }, notice: { gap: 7, padding: 13, borderRadius: 17, backgroundColor: "#F4FBF7", borderWidth: 1, borderColor: "#CBE7D9" }, noticeText: { color: "#176B43", fontSize: 12, lineHeight: 18 }, portal: { minHeight: 92, padding: 13, borderRadius: 19, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white, flexDirection: "row", alignItems: "center", gap: 12 }, portalState: { color: COLORS.earth, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, portalTitle: { color: COLORS.ink, fontSize: 15, fontWeight: "900", marginTop: 2 }, portalBody: { color: COLORS.muted, fontSize: 12, lineHeight: 17, marginTop: 4 }, viewer: { flex: 1 }, viewerHeader: { minHeight: 72, paddingHorizontal: 16, gap: 10, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.paper }, viewerTitle: { color: COLORS.ink, fontSize: 15, fontWeight: "900" }, viewerSub: { color: COLORS.muted, fontSize: 10, marginTop: 2 }, blocked: { flex: 1, padding: 28, justifyContent: "center", alignItems: "center", gap: 12 }, blockedText: { color: COLORS.muted, textAlign: "center", fontSize: 13, lineHeight: 19 }, reload: { paddingHorizontal: 14, minHeight: 42, justifyContent: "center", borderRadius: 13, backgroundColor: COLORS.indigoSoft }, reloadText: { color: COLORS.indigo, fontWeight: "900", fontSize: 12 }, webNotice: { padding: 20, borderRadius: 18, alignItems: "center", gap: 8, backgroundColor: COLORS.indigoSoft }, webNoticeTitle: { color: COLORS.indigo, fontSize: 15, fontWeight: "900" }, webNoticeText: { color: COLORS.muted, textAlign: "center", fontSize: 12, lineHeight: 18 }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
