import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { COLORS, EmptyState, IconCircle, Tag } from "@/components/lms-ui";
import { trpc } from "@/lib/trpc";

export default function FreePlaylistsScreen() {
  const router = useRouter();
  const playlistsQuery = trpc.student.freePlaylists.useQuery(undefined, { retry: 1, staleTime: 60_000 });
  const playlists = playlistsQuery.data?.playlists ?? [];
  const resources = playlistsQuery.data?.items ?? [];
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={10}><MaterialIcons name="arrow-back" size={24} color={COLORS.indigo} /></Pressable><Text style={styles.title}>Free Playlists</Text><View style={{ width: 24 }} /></View><Text style={styles.subtitle}>Open learning resources for every registered Amin Ka Master student.</Text>{playlistsQuery.isError ? <View style={styles.center}><EmptyState icon="wifi-off" title="Free resources are unavailable" body="Check your connection, then try again." /><Pressable onPress={() => void playlistsQuery.refetch()} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable></View> : playlistsQuery.isLoading ? <View style={styles.skeletonStack}>{[0, 1].map((index) => <View key={index} style={styles.skeletonPlaylist}><View style={styles.skeletonLineWide} /><View style={styles.skeletonLineShort} /><View style={styles.skeletonResource} /></View>)}</View> : playlists.length ? playlists.map((playlist) => <View key={playlist.id} style={styles.playlist}><View style={styles.playlistHead}><IconCircle icon="playlist-play" size={42} color={COLORS.indigo} /><View style={{ flex: 1 }}><Text style={styles.playlistTitle}>{playlist.title}</Text>{playlist.description ? <Text style={styles.playlistDescription}>{playlist.description}</Text> : null}</View><Tag label="FREE" tone="green" /></View>{resources.filter((resource) => resource.playlistId === playlist.id).length ? resources.filter((resource) => resource.playlistId === playlist.id).map((resource) => <Pressable key={resource.id} onPress={() => void Linking.openURL(resource.contentUrl ?? "")} style={({ pressed }) => [styles.resource, pressed && styles.pressed]}><IconCircle icon={resource.contentType === "video" ? "play-circle-filled" : "picture-as-pdf"} size={34} color={resource.contentType === "video" ? COLORS.indigo : COLORS.red} background={resource.contentType === "video" ? COLORS.indigoSoft : "#FDECEA"} /><View style={{ flex: 1 }}><Text style={styles.resourceTitle}>{resource.title}</Text><Text numberOfLines={1} style={styles.resourceMeta}>{resource.contentType === "video" ? "Recorded lecture" : "PDF note"}{resource.description ? ` · ${resource.description}` : ""}</Text></View><MaterialIcons name="open-in-new" size={19} color={COLORS.muted} /></Pressable>) : <Text style={styles.empty}>Resources will be added to this playlist soon.</Text>}</View>) : <View style={styles.center}><EmptyState icon="playlist-play" title="No free playlists yet" body="Your teachers will publish free videos and PDF notes here." /></View>}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 12, paddingBottom: 38, gap: 13 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 8 }, title: { color: COLORS.ink, fontSize: 21, fontWeight: "900" }, subtitle: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginBottom: 3 }, playlist: { gap: 10, padding: 13, borderRadius: 19, backgroundColor: COLORS.white, borderColor: COLORS.line, borderWidth: 1 }, playlistHead: { flexDirection: "row", alignItems: "center", gap: 10 }, playlistTitle: { color: COLORS.ink, fontWeight: "900", fontSize: 15 }, playlistDescription: { color: COLORS.muted, fontSize: 11, marginTop: 3, lineHeight: 16 }, resource: { minHeight: 58, borderRadius: 14, backgroundColor: COLORS.paper, padding: 9, flexDirection: "row", alignItems: "center", gap: 9 }, resourceTitle: { color: COLORS.ink, fontSize: 13, fontWeight: "800" }, resourceMeta: { color: COLORS.muted, fontSize: 10, marginTop: 3 }, empty: { color: COLORS.muted, fontSize: 12, paddingVertical: 4 }, center: { minHeight: 380, justifyContent: "center", alignItems: "center", gap: 12 }, retry: { minHeight: 44, borderRadius: 13, backgroundColor: COLORS.indigo, paddingHorizontal: 17, justifyContent: "center" }, retryText: { color: COLORS.white, fontWeight: "900" }, skeletonStack: { gap: 12 }, skeletonPlaylist: { borderRadius: 19, padding: 13, backgroundColor: COLORS.white, borderColor: COLORS.line, borderWidth: 1, gap: 10 }, skeletonLineWide: { height: 17, width: "66%", borderRadius: 6, backgroundColor: "#E9EDF3" }, skeletonLineShort: { height: 11, width: "88%", borderRadius: 5, backgroundColor: "#E9EDF3" }, skeletonResource: { height: 58, borderRadius: 14, backgroundColor: "#EEF1F5" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
});
