import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { COLORS, EmptyState, PrimaryButton, Tag } from "@/components/lms-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLmsSession } from "@/lib/lms-session";
import { trpc } from "@/lib/trpc";

export default function GuardianReportsScreen() {
  const router = useRouter();
  const { user } = useLmsSession();
  const preferenceQuery = trpc.student.guardianReportPreference.useQuery(undefined, { enabled: user?.role === "student", retry: false });
  const savePreference = trpc.student.setGuardianReportPreference.useMutation({ onSuccess: () => void preferenceQuery.refetch() });
  const [guardianName, setGuardianName] = useState("");
  const [guardianEmail, setGuardianEmail] = useState("");
  const [guardianMobile, setGuardianMobile] = useState("");
  const [consentGranted, setConsentGranted] = useState(false);
  useEffect(() => { const value = preferenceQuery.data; if (!value) return; setGuardianName(value.guardianName); setGuardianEmail(value.guardianEmail); setGuardianMobile(value.guardianMobile); setConsentGranted(value.consentGranted); }, [preferenceQuery.data]);
  const save = async () => {
    try { await savePreference.mutateAsync({ guardianName: guardianName.trim(), guardianEmail: guardianEmail.trim(), guardianMobile: guardianMobile.trim(), consentGranted }); Alert.alert("Preference saved", consentGranted ? "Authorized staff may prepare an aggregate progress report and explicitly share it with your selected parent or guardian." : "Guardian report sharing is off. Existing contact information is not used while consent remains off."); }
    catch (error) { Alert.alert("Preference not saved", error instanceof Error ? error.message : "Please check the details and try again."); }
  };
  if (user?.role !== "student") return <ScreenContainer className="px-5"><View style={styles.center}><EmptyState icon="family-restroom" title="Student access required" body="Guardian report consent is controlled only by the Student who owns the learning record." /></View></ScreenContainer>;
  if (preferenceQuery.isLoading) return <ScreenContainer className="px-5"><View style={styles.center}><ActivityIndicator color={COLORS.indigo} /><Text style={styles.loading}>Loading your consent preference…</Text></View></ScreenContainer>;
  if (preferenceQuery.isError) return <ScreenContainer className="px-5"><View style={styles.center}><EmptyState icon="wifi-off" title="Consent settings could not load" body="Check your connection and retry before changing guardian-report preferences." /><PrimaryButton label="Retry" icon="refresh" onPress={() => void preferenceQuery.refetch()} /></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Return to Account" onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={21} color={COLORS.indigo} /></Pressable><View style={{ flex: 1 }}><Text style={styles.title}>Parent/Guardian reports</Text><Text style={styles.sub}>You control whether aggregate progress may be shared</Text></View><Tag label="OPT-IN" tone="green" /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.privacy}><MaterialIcons name="privacy-tip" size={21} color={COLORS.green} /><View style={{ flex: 1 }}><Text style={styles.privacyTitle}>Your learning details stay private</Text><Text style={styles.privacyBody}>A consented report includes only active courses, overall course progress, and your study streak. It never includes test answers or marks, AI Quiz results/topics, notes, downloads, messages, or your private Study Coach plan.</Text></View></View><Field label="Parent/Guardian name" value={guardianName} onChange={setGuardianName} placeholder="For example, Parent or guardian name" /><Field label="Guardian email (optional if mobile is provided)" value={guardianEmail} onChange={setGuardianEmail} placeholder="guardian@example.com" keyboard="email-address" /><Field label="Guardian mobile (optional if email is provided)" value={guardianMobile} onChange={setGuardianMobile} placeholder="Indian mobile number" keyboard="phone-pad" /><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: consentGranted }} onPress={() => setConsentGranted((current) => !current)} style={({ pressed }) => [styles.consent, consentGranted && styles.consentOn, pressed && styles.pressed]}><MaterialIcons name={consentGranted ? "check-box" : "check-box-outline-blank"} size={23} color={consentGranted ? COLORS.green : COLORS.indigo} /><View style={{ flex: 1 }}><Text style={styles.consentTitle}>I opt in to aggregate progress sharing</Text><Text style={styles.consentBody}>Only an authorized staff member may explicitly prepare and share a report through the device share sheet. This does not create a guardian login.</Text></View></Pressable><PrimaryButton label={savePreference.isPending ? "Saving consent…" : "Save guardian-report preference"} icon="save" disabled={savePreference.isPending} onPress={() => void save()} /><Text style={styles.footer}>You can turn this off at any time. Turning consent off removes your report from the authorized staff sharing queue.</Text></ScrollView></ScreenContainer>;
}

function Field({ label, value, onChange, placeholder, keyboard = "default" }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; keyboard?: "default" | "email-address" | "phone-pad" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#98A2B3" keyboardType={keyboard} autoCapitalize={keyboard === "email-address" ? "none" : "words"} style={styles.input} /></View>; }
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", gap: 14 }, loading: { color: COLORS.muted, textAlign: "center", marginTop: 10 }, header: { minHeight: 62, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: COLORS.line }, back: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.indigoSoft }, title: { color: COLORS.ink, fontSize: 18, fontWeight: "900" }, sub: { color: COLORS.muted, fontSize: 10, marginTop: 2 }, content: { padding: 16, paddingBottom: 36, gap: 12 }, privacy: { flexDirection: "row", alignItems: "flex-start", gap: 9, padding: 13, borderRadius: 17, backgroundColor: "#F4FBF7", borderWidth: 1, borderColor: "#ABEFC6" }, privacyTitle: { color: COLORS.green, fontSize: 13, fontWeight: "900" }, privacyBody: { color: "#2B684C", fontSize: 11, lineHeight: 17, marginTop: 3 }, field: { gap: 5 }, label: { color: COLORS.ink, fontSize: 12, fontWeight: "800" }, input: { minHeight: 50, paddingHorizontal: 12, borderRadius: 13, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white, color: COLORS.ink, fontSize: 14 }, consent: { flexDirection: "row", alignItems: "flex-start", gap: 9, padding: 13, borderRadius: 16, borderWidth: 1, borderColor: "#C9D5F2", backgroundColor: COLORS.indigoSoft }, consentOn: { borderColor: "#ABEFC6", backgroundColor: "#F4FBF7" }, consentTitle: { color: COLORS.ink, fontSize: 13, fontWeight: "900" }, consentBody: { color: COLORS.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, footer: { color: COLORS.muted, fontSize: 10, textAlign: "center", lineHeight: 15 }, pressed: { opacity: .74, transform: [{ scale: .985 }] } });
