import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router";

import { COLORS, IconCircle, PrimaryButton } from "@/components/lms-ui";
import { loadManualStudyTasks, loadWeeklyLearningTime, removeManualStudyTask, type ManualStudyTask, type WeeklyLearningTime, upsertManualStudyTask } from "@/lib/study-planner";

export function WeeklyLearningGraph({ userId, onPress }: { userId: number; onPress?: () => void }) {
  const [days, setDays] = useState<WeeklyLearningTime[]>([]);
  const refresh = useCallback(() => { void loadWeeklyLearningTime(userId).then(setDays); }, [userId]);
  useFocusEffect(useCallback(() => { refresh(); }, [refresh]));
  const max = Math.max(...days.map((day) => day.seconds), 1);
  const total = days.reduce((sum, day) => sum + day.seconds, 0);
  const content = <><View style={styles.graphHeading}><View><Text style={styles.kicker}>DIGITAL WELLBEING</Text><Text style={styles.graphTitle}>Weekly learning time</Text></View><Text style={styles.total}>{total >= 3600 ? `${(total / 3600).toFixed(1)}h` : `${Math.round(total / 60)}m`}</Text></View><Text style={styles.graphCopy}>Time recorded from supported active lesson sessions on this device. It is private, local, and never sent to Staff.</Text><View style={styles.bars}>{days.map((day) => <View key={day.dayKey} style={styles.barColumn}><View style={styles.barTrack}><View style={[styles.barFill, { height: `${Math.max(3, Math.round((day.seconds / max) * 100))}%` }]} /></View><Text style={styles.barValue}>{day.seconds ? `${Math.round(day.seconds / 60)}m` : "—"}</Text><Text style={styles.barLabel}>{day.label}</Text></View>)}</View>{onPress ? <Text style={styles.openDetails}>Tap to view activity details</Text> : null}</>;
  return onPress ? <Pressable accessibilityRole="button" accessibilityLabel="Open Digital Wellbeing details" onPress={onPress} style={({ pressed }) => [styles.graph, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.graph}>{content}</View>;
}

export function EditableStudyPlanner({ userId }: { userId: number }) {
  const [tasks, setTasks] = useState<ManualStudyTask[]>([]); const [title, setTitle] = useState(""); const [detail, setDetail] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const refresh = useCallback(() => { void loadManualStudyTasks(userId).then(setTasks); }, [userId]);
  useEffect(() => { refresh(); }, [refresh]);
  const clear = () => { setTitle(""); setDetail(""); setEditingId(null); };
  const save = async () => { setSaving(true); try { setTasks(await upsertManualStudyTask(userId, { id: editingId ?? undefined, title, detail })); clear(); } finally { setSaving(false); } };
  const toggle = async (task: ManualStudyTask) => setTasks(await upsertManualStudyTask(userId, { id: task.id, title: task.title, detail: task.detail, completed: !task.completed }));
  const edit = (task: ManualStudyTask) => { setEditingId(task.id); setTitle(task.title); setDetail(task.detail); };
  const remove = async (id: string) => { setTasks(await removeManualStudyTask(userId, id)); if (editingId === id) clear(); };
  return <View style={styles.planner}><View style={styles.plannerHeading}><IconCircle icon="edit-calendar" size={38} color={COLORS.indigo} background={COLORS.indigoSoft} /><View style={{ flex: 1 }}><Text style={styles.kicker}>YOUR EDITABLE PLANNER</Text><Text style={styles.plannerTitle}>{editingId ? "Edit manual study task" : "Add a study task"}</Text></View></View><TextInput value={title} onChangeText={setTitle} placeholder="Task title, e.g. Revise chain survey" placeholderTextColor="#98A2B3" style={styles.plannerInput} maxLength={120} /><TextInput value={detail} onChangeText={setDetail} placeholder="Optional note or time target" placeholderTextColor="#98A2B3" style={[styles.plannerInput, styles.plannerDetail]} multiline maxLength={240} textAlignVertical="top" /><View style={styles.plannerActions}><PrimaryButton label={saving ? "Saving…" : editingId ? "Save task changes" : "Add task"} icon={editingId ? "save" : "add-task"} disabled={saving || !title.trim()} onPress={() => void save()} />{editingId ? <Pressable onPress={clear} style={styles.cancel}><Text style={styles.cancelText}>Cancel edit</Text></Pressable> : null}</View>{tasks.length ? <View style={styles.taskList}>{tasks.map((task) => <View key={task.id} style={[styles.manualTask, task.completed && styles.manualTaskDone]}><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: task.completed }} onPress={() => void toggle(task)} style={styles.check}><MaterialIcons name={task.completed ? "check-circle" : "radio-button-unchecked"} size={22} color={task.completed ? COLORS.green : COLORS.indigo} /></Pressable><Pressable onPress={() => edit(task)} style={{ flex: 1 }}><Text style={[styles.taskTitle, task.completed && styles.taskTitleDone]}>{task.title}</Text>{task.detail ? <Text style={styles.taskDetail}>{task.detail}</Text> : null}</Pressable><Pressable accessibilityLabel={`Delete ${task.title}`} onPress={() => void remove(task.id)} style={styles.delete}><MaterialIcons name="delete-outline" size={19} color={COLORS.red} /></Pressable></View>)}</View> : <Text style={styles.empty}>Add personal tasks alongside the Coach’s evidence-based recommendations. Manual tasks remain private to this device.</Text>}</View>;
}

const styles = StyleSheet.create({ graph: { marginTop: 12, padding: 14, borderRadius: 19, borderWidth: 1, borderColor: "#C9D5F2", backgroundColor: "#F8FAFF" }, openDetails: { color: COLORS.indigo, fontSize: 10, fontWeight: "900", marginTop: 10 }, pressed: { opacity: .74, transform: [{ scale: .985 }] }, graphHeading: { flexDirection: "row", justifyContent: "space-between", gap: 8, alignItems: "center" }, kicker: { color: COLORS.indigo, fontSize: 10, fontWeight: "900", letterSpacing: .8 }, graphTitle: { color: COLORS.ink, fontSize: 16, fontWeight: "900", marginTop: 3 }, total: { color: COLORS.indigo, fontSize: 19, fontWeight: "900" }, graphCopy: { color: COLORS.muted, fontSize: 10, lineHeight: 15, marginTop: 5 }, bars: { height: 136, marginTop: 14, flexDirection: "row", justifyContent: "space-between", gap: 6, alignItems: "flex-end" }, barColumn: { flex: 1, alignItems: "center", gap: 4 }, barTrack: { width: "100%", height: 82, backgroundColor: "#E1E8F5", borderRadius: 7, justifyContent: "flex-end", overflow: "hidden" }, barFill: { width: "100%", minHeight: 3, borderRadius: 7, backgroundColor: COLORS.indigo }, barValue: { color: COLORS.indigo, fontSize: 9, fontWeight: "800" }, barLabel: { color: COLORS.muted, fontSize: 9, fontWeight: "800" }, planner: { marginTop: 12, padding: 14, gap: 9, borderRadius: 19, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, plannerHeading: { flexDirection: "row", alignItems: "center", gap: 9 }, plannerTitle: { color: COLORS.ink, fontSize: 15, fontWeight: "900", marginTop: 2 }, plannerInput: { minHeight: 48, paddingHorizontal: 12, borderRadius: 13, borderWidth: 1, borderColor: COLORS.line, backgroundColor: "#FFF", color: COLORS.ink, fontSize: 13 }, plannerDetail: { minHeight: 68, paddingTop: 10 }, plannerActions: { gap: 8 }, cancel: { alignSelf: "center", minHeight: 34, justifyContent: "center", paddingHorizontal: 10 }, cancelText: { color: COLORS.indigo, fontSize: 12, fontWeight: "900" }, taskList: { gap: 8, marginTop: 3 }, manualTask: { minHeight: 56, padding: 9, borderRadius: 13, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#F8FAFC", borderWidth: 1, borderColor: COLORS.line }, manualTaskDone: { backgroundColor: "#F4FBF7", borderColor: "#ABEFC6" }, check: { width: 30, minHeight: 38, alignItems: "center", justifyContent: "center" }, taskTitle: { color: COLORS.ink, fontSize: 12, fontWeight: "900" }, taskTitleDone: { color: COLORS.muted, textDecorationLine: "line-through" }, taskDetail: { color: COLORS.muted, marginTop: 2, fontSize: 10, lineHeight: 14 }, delete: { width: 34, minHeight: 38, justifyContent: "center", alignItems: "center" }, empty: { color: COLORS.muted, fontSize: 11, lineHeight: 16, marginTop: 2 } });
