import { INDIA_STATES, LAND_UNIT_LABELS, type RecentConversion } from "@/lib/amin-toolkit";

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character] ?? character));
}

export function buildLandConversionReportHtml(entries: RecentConversion[], generatedAt = new Date()) {
  const rows = entries.map((entry, index) => {
    const state = INDIA_STATES.find((item) => item.code === entry.stateCode)?.name ?? entry.stateCode;
    return `<tr><td>${index + 1}</td><td>${escapeHtml(entry.amount.toLocaleString("en-IN"))}</td><td>${escapeHtml(LAND_UNIT_LABELS[entry.from])}</td><td>${escapeHtml(LAND_UNIT_LABELS[entry.to])}</td><td>${escapeHtml(state)}${entry.districtOrTehsil ? `<br /><span>${escapeHtml(entry.districtOrTehsil)}</span>` : ""}</td><td>${escapeHtml(new Date(entry.createdAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }))}</td></tr>`;
  }).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8" /><style>@page{margin:28px}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#14213d;font-size:12px;line-height:1.45}.header{padding:20px;border:3px solid #14213d;background:#f8f5ed}.brand{color:#b15d22;font-size:10px;font-weight:700;letter-spacing:1.6px}.title{font-size:25px;margin:6px 0}.copy{color:#596579;margin:3px 0}table{width:100%;border-collapse:collapse;margin-top:20px}th{background:#14213d;color:#fff;text-align:left;font-size:10px;letter-spacing:.5px}th,td{padding:9px 8px;border:1px solid #d0d5dd;vertical-align:top}tr:nth-child(even){background:#f8fafc}span{color:#667085;font-size:10px}.notice{margin-top:18px;padding:11px;border-left:4px solid #b15d22;background:#fff8e9;color:#7a4a17}.footer{margin-top:24px;padding-top:10px;border-top:1px solid #d0d5dd;color:#667085;font-size:10px}</style></head><body><header class="header"><p class="brand">AMIN KA MASTER · PRIVATE TOOLKIT</p><h1 class="title">Recent land measurement conversions</h1><p class="copy">Generated on ${escapeHtml(generatedAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }))}</p><p class="copy">${entries.length} device-local conversion${entries.length === 1 ? "" : "s"} included</p></header><table><thead><tr><th>#</th><th>Amount</th><th>From</th><th>To</th><th>State / district context</th><th>Saved</th></tr></thead><tbody>${rows}</tbody></table><section class="notice"><strong>Reference only.</strong> Traditional local units vary by district and tehsil. Confirm the selected profile against the relevant official record before relying on a conversion. This report is not a legal land record, certified survey, or boundary determination.</section><footer class="footer">Generated locally from private Amin Ka Master Toolkit history. This export is not uploaded to the learning platform.</footer></body></html>`;
}
