import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { COLORS, EmptyState, PrimaryButton, Tag } from "@/components/lms-ui";
import { useLmsSession } from "@/lib/lms-session";
import { trpc } from "@/lib/trpc";

export default function AiQuizReviewsScreen() {
  const router = useRouter();
  const { user } = useLmsSession();
  const queueQuery = trpc.operations.aiQuizReviewQueue.useQuery(undefined, { enabled: Boolean(user && user.role !== "student"), retry: 1 });
  const utils = trpc.useUtils();
  const exportMutation = trpc.operations.exportAiQuizReview.useMutation({ onSuccess: async () => { await utils.operations.aiQuizReviewQueue.invalidate(); await utils.operations.tests.invalidate(); } });
  if (!user || user.role === "student") return <ScreenContainer className="items-center justify-center px-5"><Text style={styles.denied}>Operations permission is required.</Text></ScreenContainer>;
  const exportSubmission = (submissionId: number, topic: string, count: number) => Alert.alert("Export reviewed questions?", `${count} AI-generated questions about ${topic} will create an unpublished draft test. Review and edit it before publishing.`, [{ text: "Cancel", style: "cancel" }, { text: "Create draft", onPress: () => void exportMutation.mutateAsync({ submissionId }).then((result) => router.push(`/operations/tests/${result.testId}` as never)).catch((error) => Alert.alert("Draft not created", error instanceof Error ? error.message : "Please try again.")) }]);
  if (queueQuery.isLoading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={COLORS.indigo} /></ScreenContainer>;
  if (queueQuery.isError) return <ScreenContainer className="items-center justify-center px-5"><EmptyState icon="wifi-off" title="AI Quiz review could not load" body="Retry when the operations server is available." /><PrimaryButton label="Retry" icon="refresh" onPress={() => void queueQuery.refetch()} /></ScreenContainer>;
  const pending = (queueQuery.data ?? []).filter((item) => item.submission.status === "pending");
  return <ScreenContainer edges={["top", "left", "right"]}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Return to test manager" onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={COLORS.indigo} /></Pressable><View style={{ flex: 1 }}><Text style={styles.title}>AI Quiz review</Text><Text style={styles.sub}>Consent-based Student submissions only</Text></View><Tag label={`${pending.length} PENDING`} tone="saffron" /></View><FlatList data={pending} keyExtractor={(item) => item.submission.id.toString()} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><EmptyState icon="rate-review" title="No AI Quiz reviews" body="Student practice sets appear here only after the Student chooses to send them for teacher review." /></View>} renderItem={({ item }) => { const questions = item.submission.questions as { question: string; options: string[]; correctIndex: number; explanation: string }[]; return <View style={styles.card}><View style={styles.cardHeader}><View style={{ flex: 1 }}><Text style={styles.topic}>{item.submission.topic}</Text><Text style={styles.meta}>{item.studentName ?? "Student"} · {item.submission.difficulty} · {item.submission.language}</Text></View><Tag label={`${questions.length} MCQs`} tone="neutral" /></View><Text numberOfLines={2} style={styles.preview}>{questions[0]?.question ?? "Question preview unavailable"}</Text><Text style={styles.boundary}>Validate wording, answers, and explanations after export. Drafts are never auto-published.</Text><PrimaryButton label={exportMutation.isPending && exportMutation.variables?.submissionId === item.submission.id ? "Creating draft…" : "Export to draft test"} icon="assignment" disabled={exportMutation.isPending} onPress={() => exportSubmission(item.submission.id, item.submission.topic, questions.length)} /></View>; }} /></ScreenContainer>;
}

const styles = StyleSheet.create({ header: { minHeight: 64, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: COLORS.line }, back: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.indigoSoft }, title: { color: COLORS.ink, fontSize: 20, fontWeight: "900" }, sub: { color: COLORS.muted, fontSize: 11, marginTop: 2 }, list: { padding: 16, gap: 12 }, card: { gap: 10, padding: 14, borderRadius: 18, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, cardHeader: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, topic: { color: COLORS.ink, fontSize: 16, fontWeight: "900" }, meta: { color: COLORS.muted, fontSize: 11, marginTop: 4 }, preview: { color: COLORS.ink, fontSize: 13, lineHeight: 19, padding: 10, borderRadius: 12, backgroundColor: COLORS.paper }, boundary: { color: COLORS.green, fontSize: 11, lineHeight: 16 }, empty: { paddingTop: 80 }, denied: { color: COLORS.muted, textAlign: "center" } });
