import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { COLORS, EmptyState, IconCircle, PrimaryButton, Tag } from "@/components/lms-ui";
import { useLmsSession } from "@/lib/lms-session";
import { trpc } from "@/lib/trpc";

type Tab = "settings" | "people" | "business" | "activity";
type ControlForm = { appName: string; tagline: string; heroTitle: string; heroSubtitle: string; heroCta: string; contactEmail: string; contactPhone: string; whatsapp: string; showLive: boolean; registrationEnabled: boolean; maintenanceEnabled: boolean };
const initialForm: ControlForm = { appName: "", tagline: "", heroTitle: "", heroSubtitle: "", heroCta: "", contactEmail: "", contactPhone: "", whatsapp: "", showLive: true, registrationEnabled: true, maintenanceEnabled: false };

export default function SuperAdminControlScreen() {
  const router = useRouter();
  const { user } = useLmsSession();
  const enabled = user?.role === "super_admin";
  const [tab, setTab] = useState<Tab>("settings");
  const [form, setForm] = useState<ControlForm>(initialForm);
  const [announcementTitle, setAnnouncementTitle] = useState("");
  const [announcementBody, setAnnouncementBody] = useState("");
  const [publishAnnouncement, setPublishAnnouncement] = useState(true);
  const settingsQuery = trpc.operations.masterSettings.useQuery(undefined, { enabled, retry: false });
  const peopleQuery = trpc.operations.people.useQuery(undefined, { enabled, retry: false });
  const enrollmentQuery = trpc.operations.enrollments.useQuery(undefined, { enabled, retry: false });
  const orderQuery = trpc.operations.orders.useQuery(undefined, { enabled, retry: false });
  const reviewQuery = trpc.operations.reviews.useQuery(undefined, { enabled, retry: false });
  const announcementQuery = trpc.operations.announcements.useQuery(undefined, { enabled, retry: false });
  const auditQuery = trpc.operations.auditLogs.useQuery(undefined, { enabled, retry: false });
  const saveSettingsMutation = trpc.operations.saveMasterSettings.useMutation({ onSuccess: () => void settingsQuery.refetch() });
  const personMutation = trpc.operations.updatePerson.useMutation({ onSuccess: () => void peopleQuery.refetch() });
  const enrollmentMutation = trpc.operations.setEnrollmentStatus.useMutation({ onSuccess: () => void enrollmentQuery.refetch() });
  const reviewMutation = trpc.operations.setReviewStatus.useMutation({ onSuccess: () => void reviewQuery.refetch() });
  const announcementMutation = trpc.operations.createAnnouncement.useMutation({ onSuccess: () => void announcementQuery.refetch() });

  useEffect(() => {
    const values = settingsQuery.data;
    if (!values) return;
    const string = (key: string) => typeof values[key as keyof typeof values] === "string" ? String(values[key as keyof typeof values]) : "";
    const bool = (key: string, fallback: boolean) => typeof values[key as keyof typeof values] === "boolean" ? Boolean(values[key as keyof typeof values]) : fallback;
    setForm({ appName: string("brand.app_name"), tagline: string("brand.tagline"), heroTitle: string("homepage.hero_title"), heroSubtitle: string("homepage.hero_subtitle"), heroCta: string("homepage.hero_cta"), contactEmail: string("brand.contact_email"), contactPhone: string("brand.contact_phone"), whatsapp: string("brand.whatsapp"), showLive: bool("homepage.show_live", true), registrationEnabled: bool("platform.registration_enabled", true), maintenanceEnabled: bool("platform.maintenance_enabled", false) });
  }, [settingsQuery.data]);

  if (!enabled) return <ScreenContainer className="items-center justify-center px-5"><EmptyState icon="admin-panel-settings" title="Owner access required" body="This control center is reserved for Super Admin accounts, and the server repeats the restriction." /></ScreenContainer>;
  if (settingsQuery.isLoading || peopleQuery.isLoading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={COLORS.indigo} /></ScreenContainer>;

  const saveSettings = async () => { try { await saveSettingsMutation.mutateAsync(form); Alert.alert("Saved", "Brand, homepage and operating settings are stored in the Admin control system."); } catch (error) { Alert.alert("Settings not saved", error instanceof Error ? error.message : "Please try again."); } };
  const createAnnouncement = async () => { if (announcementTitle.trim().length < 3 || announcementBody.trim().length < 3) return Alert.alert("Complete the announcement", "Add a title and message."); try { await announcementMutation.mutateAsync({ title: announcementTitle.trim(), body: announcementBody.trim(), targetType: "all_students", isPublished: publishAnnouncement }); setAnnouncementTitle(""); setAnnouncementBody(""); Alert.alert("Announcement saved", publishAnnouncement ? "It is now published for students." : "It remains a draft."); } catch (error) { Alert.alert("Announcement not saved", error instanceof Error ? error.message : "Please try again."); } };

  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}>
    <View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-back" size={23} color={COLORS.indigo} /></Pressable><View style={styles.heading}><Text style={styles.eyebrow}>SUPER ADMIN / OWNER</Text><Text style={styles.title}>Control Center</Text></View><IconCircle icon="admin-panel-settings" size={37} color={COLORS.saffron} background={COLORS.indigo} /></View>
    <View style={styles.tabs}><TabButton label="Settings" icon="tune" active={tab === "settings"} onPress={() => setTab("settings")} /><TabButton label="People" icon="groups" active={tab === "people"} onPress={() => setTab("people")} /><TabButton label="Business" icon="business-center" active={tab === "business"} onPress={() => setTab("business")} /><TabButton label="Activity" icon="history" active={tab === "activity"} onPress={() => setTab("activity")} /></View>
    {tab === "settings" && <SettingsPanel form={form} setForm={setForm} saving={saveSettingsMutation.isPending} onSave={saveSettings} />}
    {tab === "people" && <PeoplePanel items={peopleQuery.data ?? []} onUpdate={(input: any) => void personMutation.mutateAsync(input)} />}
    {tab === "business" && <BusinessPanel enrollments={enrollmentQuery.data ?? []} reviews={reviewQuery.data ?? []} orders={orderQuery.data ?? []} title={announcementTitle} body={announcementBody} published={publishAnnouncement} setTitle={setAnnouncementTitle} setBody={setAnnouncementBody} setPublished={setPublishAnnouncement} saving={announcementMutation.isPending} onCreate={createAnnouncement} onEnrollment={(input: any) => void enrollmentMutation.mutateAsync(input)} onReview={(input: any) => void reviewMutation.mutateAsync(input)} />}
    {tab === "activity" && <ActivityPanel announcements={announcementQuery.data ?? []} audits={auditQuery.data ?? []} />}
  </ScreenContainer>;
}

function SettingsPanel({ form, setForm, saving, onSave }: { form: ControlForm; setForm: React.Dispatch<React.SetStateAction<ControlForm>>; saving: boolean; onSave: () => void }) {
  const update = (key: keyof ControlForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value } as ControlForm));
  return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Text style={styles.helper}>Operate normal business content here. Passwords, payment secrets, database credentials and private API keys are not exposed in this interface.</Text><Text style={styles.section}>Brand and contact</Text><Field label="App name" value={form.appName} onChangeText={(value) => update("appName", value)} /><Field label="Tagline" value={form.tagline} onChangeText={(value) => update("tagline", value)} /><Field label="Contact email" value={form.contactEmail} onChangeText={(value) => update("contactEmail", value)} /><Field label="Contact phone" value={form.contactPhone} onChangeText={(value) => update("contactPhone", value)} /><Field label="WhatsApp" value={form.whatsapp} onChangeText={(value) => update("whatsapp", value)} /><Text style={styles.section}>Homepage</Text><Field label="Hero title" value={form.heroTitle} onChangeText={(value) => update("heroTitle", value)} /><Field label="Hero subtitle" value={form.heroSubtitle} onChangeText={(value) => update("heroSubtitle", value)} /><Field label="Hero button label" value={form.heroCta} onChangeText={(value) => update("heroCta", value)} /><Toggle label="Show live-class highlight" value={form.showLive} onValueChange={(value) => update("showLive", value)} /><Text style={styles.section}>Platform safeguards</Text><Toggle label="Allow new registrations" value={form.registrationEnabled} onValueChange={(value) => update("registrationEnabled", value)} /><Toggle label="Maintenance mode" value={form.maintenanceEnabled} onValueChange={(value) => update("maintenanceEnabled", value)} /><PrimaryButton label={saving ? "Saving…" : "Save control settings"} icon="save" onPress={onSave} disabled={saving} /></ScrollView>;
}

function PeoplePanel({ items, onUpdate }: { items: any[]; onUpdate: (input: any) => void }) {
  const nextRole = (role: "student" | "teacher" | "admin") => role === "student" ? "teacher" : role === "teacher" ? "admin" : "student";
  return <FlatList data={items} keyExtractor={(item) => item.id.toString()} contentContainerStyle={styles.list} ListHeaderComponent={<Text style={styles.helper}>Manage student, teacher and admin access. Super Admin accounts cannot be changed here and passwords are never shown.</Text>} renderItem={({ item }) => <View style={styles.row}><IconCircle icon={item.role === "student" ? "person" : "manage-accounts"} size={40} /><View style={styles.copy}><Text style={styles.rowTitle}>{item.fullName ?? "Unnamed account"}</Text><Text style={styles.meta}>{item.email ?? item.mobile ?? "No contact details"}</Text><View style={styles.tags}><Tag label={item.role.replace("_", " ").toUpperCase()} tone={item.role === "student" ? "indigo" : "saffron"} /><Tag label={item.status.toUpperCase()} tone={item.status === "active" ? "green" : "red"} /></View></View>{item.role !== "super_admin" && <View style={styles.actions}><Pressable onPress={() => onUpdate({ userId: item.id, role: nextRole(item.role) })} style={styles.small}><Text style={styles.smallText}>Role</Text></Pressable><Pressable onPress={() => onUpdate({ userId: item.id, status: item.status === "active" ? "suspended" : "active" })} style={styles.small}><Text style={styles.smallText}>{item.status === "active" ? "Suspend" : "Activate"}</Text></Pressable></View>}</View>} />;
}

function BusinessPanel({ enrollments, reviews, orders, title, body, published, setTitle, setBody, setPublished, saving, onCreate, onEnrollment, onReview }: any) {
  const rows = [ ...enrollments.map((value: any) => ({ type: "enrollment", value })), ...reviews.map((value: any) => ({ type: "review", value })), ...orders.map((value: any) => ({ type: "order", value })) ];
  const nextEnrollment = (status: "active" | "expired" | "revoked") => status === "active" ? "expired" : status === "expired" ? "revoked" : "active";
  const nextReview = (status: "pending" | "approved" | "hidden") => status === "pending" ? "approved" : status === "approved" ? "hidden" : "pending";
  return <FlatList data={rows} keyExtractor={(_, index) => String(index)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.businessTop}><Text style={styles.section}>Student announcement</Text><TextInput value={title} onChangeText={setTitle} placeholder="Announcement title" placeholderTextColor="#98A2B3" style={styles.input} /><TextInput value={body} onChangeText={setBody} placeholder="Message for all students" placeholderTextColor="#98A2B3" multiline textAlignVertical="top" style={[styles.input, styles.area]} /><Toggle label="Publish immediately" value={published} onValueChange={setPublished} /><PrimaryButton label={saving ? "Saving…" : "Save announcement"} icon="campaign" onPress={onCreate} disabled={saving} /><Text style={styles.section}>Enrollments, reviews and orders</Text><Text style={styles.helper}>Orders are read-only. Payment state can only be activated from a verified server-side provider event.</Text></View>} renderItem={({ item }) => item.type === "enrollment" ? <EnrollmentRow item={item.value} onPress={() => onEnrollment({ enrollmentId: item.value.enrollment.id, status: nextEnrollment(item.value.enrollment.status) })} /> : item.type === "review" ? <ReviewRow item={item.value} onPress={() => onReview({ reviewId: item.value.review.id, status: nextReview(item.value.review.status) })} /> : <OrderRow item={item.value} />} />;
}

function EnrollmentRow({ item, onPress }: { item: any; onPress: () => void }) { return <View style={styles.row}><IconCircle icon="school" size={40} color={COLORS.green} background={COLORS.greenSoft} /><View style={styles.copy}><Text style={styles.rowTitle}>{item.studentName ?? "Student"}</Text><Text style={styles.meta}>{item.courseTitle}</Text><Tag label={item.enrollment.status.toUpperCase()} tone={item.enrollment.status === "active" ? "green" : "neutral"} /></View><Pressable onPress={onPress} style={styles.small}><Text style={styles.smallText}>Status</Text></Pressable></View>; }
function ReviewRow({ item, onPress }: { item: any; onPress: () => void }) { return <View style={styles.row}><IconCircle icon="star-outline" size={40} color={COLORS.saffron} background="#FFF1DE" /><View style={styles.copy}><Text style={styles.rowTitle}>{item.courseTitle} · {item.review.rating}/5</Text><Text numberOfLines={2} style={styles.meta}>{item.review.body}</Text><Tag label={item.review.status.toUpperCase()} tone={item.review.status === "approved" ? "green" : "saffron"} /></View><Pressable onPress={onPress} style={styles.small}><Text style={styles.smallText}>Moderate</Text></Pressable></View>; }
function OrderRow({ item }: { item: any }) { return <View style={styles.row}><IconCircle icon="receipt-long" size={40} color={COLORS.indigo} background={COLORS.indigoSoft} /><View style={styles.copy}><Text style={styles.rowTitle}>{item.courseTitle}</Text><Text style={styles.meta}>{item.studentName ?? "Student"} · ₹{item.order.amount}</Text><Tag label={item.order.status.toUpperCase()} tone={item.order.status === "paid" ? "green" : item.order.status === "failed" ? "red" : "saffron"} /></View></View>; }

function ActivityPanel({ announcements, audits }: { announcements: any[]; audits: any[] }) { return <FlatList data={audits} keyExtractor={(item) => item.audit.id.toString()} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.businessTop}><Text style={styles.section}>Recent announcements</Text>{announcements.slice(0, 3).map((item) => <View key={item.id} style={styles.announcement}><Text style={styles.rowTitle}>{item.title}</Text><Text numberOfLines={2} style={styles.meta}>{item.body}</Text><Tag label={item.isPublished ? "PUBLISHED" : "DRAFT"} tone={item.isPublished ? "green" : "saffron"} /></View>)}<Text style={styles.section}>Audit trail</Text><Text style={styles.helper}>Actor, action, target and time are recorded. Sensitive values such as passwords and private keys are never logged.</Text></View>} renderItem={({ item }) => <View style={styles.audit}><IconCircle icon="history" size={35} color={COLORS.earth} background="#FFF1DE" /><View style={styles.copy}><Text style={styles.rowTitle}>{item.audit.action.replaceAll("_", " ")}</Text><Text style={styles.meta}>{item.actorName ?? "System"} · {new Date(item.audit.createdAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</Text><Text style={styles.auditMeta}>{item.audit.entityType}{item.audit.entityId ? ` #${item.audit.entityId}` : ""}</Text></View></View>} />; }

function TabButton({ label, icon, active, onPress }: { label: string; icon: React.ComponentProps<typeof MaterialIcons>["name"]; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.tab, active && styles.tabActive]}><MaterialIcons name={icon} size={17} color={active ? COLORS.white : COLORS.muted} /><Text style={[styles.tabText, active && styles.tabTextActive]}>{label}</Text></Pressable>; }
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={label} placeholderTextColor="#98A2B3" style={styles.input} /></View>; }
function Toggle({ label, value, onValueChange }: { label: string; value: boolean; onValueChange: (value: boolean) => void }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} onValueChange={onValueChange} trackColor={{ false: COLORS.line, true: COLORS.indigo }} /></View>; }

const styles = StyleSheet.create({ header:{paddingTop:11,paddingBottom:12,flexDirection:"row",alignItems:"center",gap:10},heading:{flex:1},eyebrow:{color:COLORS.earth,fontSize:10,fontWeight:"900",letterSpacing:1},title:{color:COLORS.ink,fontSize:22,fontWeight:"900"},tabs:{flexDirection:"row",gap:6,marginBottom:12},tab:{flex:1,minHeight:43,borderRadius:12,borderWidth:1,borderColor:COLORS.line,alignItems:"center",justifyContent:"center",gap:3,backgroundColor:COLORS.white},tabActive:{backgroundColor:COLORS.indigo,borderColor:COLORS.indigo},tabText:{color:COLORS.muted,fontSize:10,fontWeight:"900"},tabTextActive:{color:COLORS.white},scroll:{paddingBottom:36,gap:10},helper:{borderRadius:13,backgroundColor:COLORS.indigoSoft,color:COLORS.indigo,padding:11,fontSize:12,lineHeight:18},section:{color:COLORS.ink,fontSize:17,fontWeight:"900",marginTop:10},field:{gap:5},label:{color:COLORS.ink,fontSize:12,fontWeight:"800"},input:{minHeight:50,borderWidth:1,borderColor:COLORS.line,borderRadius:13,backgroundColor:COLORS.white,paddingHorizontal:12,color:COLORS.ink,fontSize:14},area:{minHeight:88,paddingTop:12},toggle:{minHeight:52,paddingHorizontal:13,borderRadius:13,borderWidth:1,borderColor:COLORS.line,backgroundColor:COLORS.white,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},toggleLabel:{color:COLORS.ink,fontSize:14,fontWeight:"800"},list:{gap:10,paddingBottom:35},row:{backgroundColor:COLORS.white,borderColor:COLORS.line,borderWidth:1,borderRadius:17,padding:12,flexDirection:"row",alignItems:"center",gap:9},copy:{flex:1,gap:3},rowTitle:{color:COLORS.ink,fontSize:14,fontWeight:"900"},meta:{color:COLORS.muted,fontSize:11,lineHeight:16},tags:{flexDirection:"row",gap:5,alignItems:"center"},actions:{alignItems:"flex-end",gap:5},small:{minHeight:28,paddingHorizontal:8,borderRadius:9,backgroundColor:COLORS.indigoSoft,alignItems:"center",justifyContent:"center"},smallText:{color:COLORS.indigo,fontSize:10,fontWeight:"900"},businessTop:{gap:10},announcement:{borderRadius:14,borderWidth:1,borderColor:COLORS.line,backgroundColor:COLORS.white,padding:11,gap:5},audit:{borderRadius:15,borderWidth:1,borderColor:COLORS.line,backgroundColor:COLORS.white,padding:11,flexDirection:"row",gap:9,alignItems:"center"},auditMeta:{color:COLORS.earth,fontSize:10,fontWeight:"800"} });
