import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { VideoView, useVideoPlayer } from "expo-video";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { COLORS, EmptyState, PrimaryButton, Tag } from "@/components/lms-ui";
import { useLmsSession } from "@/lib/lms-session";
import { trpc } from "@/lib/trpc";

export default function ModerationScreen() {
  const router = useRouter(); const { user } = useLmsSession(); const enabled = user?.role === "admin" || user?.role === "super_admin";
  const queueQuery = trpc.operations.pendingShorts.useQuery(undefined, { enabled, retry: false });
  const moderateMutation = trpc.operations.moderateShort.useMutation({ onSuccess: () => void queueQuery.refetch() });
  const [selectedId, setSelectedId] = useState<number | null>(null); const [note, setNote] = useState("");
  const selected = (queueQuery.data ?? []).find((item) => item.id === selectedId) ?? null;
  const decide = (decision: "approved" | "rejected") => { if (!selected) return; const verb = decision === "approved" ? "Approve and publish" : "Reject submission"; Alert.alert(verb, decision === "approved" ? "This will publish the Short globally for students." : "This keeps the Short out of the public feed and records the moderator note.", [{ text: "Cancel", style: "cancel" }, { text: verb, style: decision === "rejected" ? "destructive" : "default", onPress: () => void moderateMutation.mutateAsync({ shortId: selected.id, decision, moderationNote: note.trim() || undefined }).then(() => { setSelectedId(null); setNote(""); }).catch((error) => Alert.alert("Moderation not saved", error instanceof Error ? error.message : "Try again.")) }]); };
  if (!enabled) return <ScreenContainer className="items-center justify-center px-5"><EmptyState icon="lock" title="Moderation access required" body="Only Admin and Owner accounts can approve or reject student Shorts." /></ScreenContainer>;
  if (queueQuery.isLoading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={COLORS.indigo} /></ScreenContainer>;
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={COLORS.indigo} /></Pressable><View><Text style={styles.eyebrow}>CONTENT SAFETY</Text><Text style={styles.title}>Student Short moderation</Text></View></View><Text style={styles.helper}>Student videos remain private until an Admin or Owner explicitly approves them. Approvals and rejections are recorded in the audit trail.</Text>{queueQuery.isError ? <EmptyState icon="wifi-off" title="Queue could not load" body="Check the connection and retry." action={<PrimaryButton label="Retry" icon="refresh" onPress={() => void queueQuery.refetch()} />} /> : !(queueQuery.data ?? []).length ? <EmptyState icon="verified" title="Nothing pending" body="There are no student Short submissions awaiting review." /> : <>{(queueQuery.data ?? []).map((item) => <Pressable key={item.id} onPress={() => { setSelectedId(item.id); setNote(""); }} style={[styles.row, item.id === selectedId && styles.selected]}><View style={styles.thumb}><MaterialIcons name="play-circle-filled" size={31} color={COLORS.indigo} /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowMeta}>{item.authorName ?? "Student"} · {new Date(item.createdAt).toLocaleDateString("en-IN")}</Text></View><Tag label="PENDING" tone="saffron" /></Pressable>)}{selected ? <ReviewCard item={selected} note={note} setNote={setNote} busy={moderateMutation.isPending} onApprove={() => decide("approved")} onReject={() => decide("rejected")} /> : null}</>}</ScrollView></ScreenContainer>;
}
function ReviewCard({ item, note, setNote, busy, onApprove, onReject }: { item: { id: number; videoUrl: string; description: string | null; authorName: string | null; authorEmail: string | null; authorMobile: string | null }; note: string; setNote: (value: string) => void; busy: boolean; onApprove: () => void; onReject: () => void }) { const player = useVideoPlayer(item.videoUrl, (video) => { video.loop = true; }); return <View style={styles.review}><Text style={styles.reviewTitle}>Review selected Short</Text><VideoView player={player} nativeControls contentFit="contain" style={styles.video} /><Text style={styles.detail}>{item.description || "No student description provided."}</Text><Text style={styles.detail}>Submitted by {item.authorName ?? "Student"} · {item.authorEmail ?? item.authorMobile ?? "No contact detail"}</Text><TextInput value={note} onChangeText={setNote} placeholder="Optional moderation note (shown only to staff)" placeholderTextColor="#98A2B3" multiline style={styles.note} /><View style={styles.actions}><PrimaryButton label={busy ? "Saving…" : "Approve & publish"} icon="check-circle" disabled={busy} onPress={onApprove} /><PrimaryButton label="Reject" icon="block" subtle disabled={busy} onPress={onReject} /></View></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 38, gap: 11 }, header: { flexDirection: "row", gap: 10, alignItems: "center" }, back: { width: 42, height: 42, borderRadius: 14, justifyContent: "center", alignItems: "center", backgroundColor: COLORS.indigoSoft }, eyebrow: { color: COLORS.earth, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: COLORS.ink, fontSize: 21, fontWeight: "900" }, helper: { color: COLORS.indigo, backgroundColor: COLORS.indigoSoft, borderRadius: 14, padding: 12, fontSize: 12, lineHeight: 18 }, row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 16, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white, padding: 10 }, selected: { borderColor: COLORS.indigo, backgroundColor: COLORS.indigoSoft }, thumb: { width: 45, height: 45, borderRadius: 14, justifyContent: "center", alignItems: "center", backgroundColor: COLORS.indigoSoft }, rowTitle: { color: COLORS.ink, fontSize: 14, fontWeight: "900" }, rowMeta: { color: COLORS.muted, fontSize: 11, marginTop: 3 }, review: { gap: 10, borderRadius: 18, borderWidth: 1, borderColor: COLORS.indigo, backgroundColor: COLORS.white, padding: 13 }, reviewTitle: { color: COLORS.ink, fontSize: 16, fontWeight: "900" }, video: { width: "100%", height: 230, borderRadius: 13, backgroundColor: COLORS.indigo }, detail: { color: COLORS.muted, fontSize: 12, lineHeight: 18 }, note: { minHeight: 75, borderRadius: 13, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.paper, paddingHorizontal: 11, paddingTop: 10, color: COLORS.ink, textAlignVertical: "top" }, actions: { gap: 8 } });
